# 1. Creating NumPy Arrays

In [33]:
# Step 1: Import NumPy 
import numpy as np 
# Step 2: Create a 1D array representing years of experience 
years_exp = np.array([1, 3, 5, 7, 10]) 
print("Years of Experience:", years_exp) 
# Step 3: Create a 2D array representing sample salaries (in thousands) 
salaries = np.array([[50, 60, 70], [80, 90, 100]]) 
print("Salary Matrix:\n", salaries) 
# Step 4: Create an array of zeros and ones for placeholder analysis 
zeros_array = np.zeros((2, 2)) # 2x2 zeros 
ones_array = np.ones((2, 3)) # 2x3 ones 
print("Zeros Array:\n", zeros_array) 
print("Ones Array:\n", ones_array)


Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


### Try it for number 1:

In [34]:
import numpy as np

# Original Setup [cite: 42, 44, 47]
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], [80, 90, 100]])

# Try It: Add 2 data points and create a 3x3 identity matrix [cite: 58]
years_exp = np.append(years_exp, [12, 15])
salaries = np.append(salaries, [[110, 120, 130]], axis=0) # Adding a row to make it 3x3
identity_3x3 = np.eye(3)

print("Updated Years:", years_exp)
print("Updated Salaries:\n", salaries)
print("3x3 Identity Matrix:\n", identity_3x3)


Updated Years: [ 1  3  5  7 10 12 15]
Updated Salaries:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 2. Array Operations

In [35]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)
# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)
# Step 3: Dot product (simulate salary projections)
sample1 = np.array ([1, 2, 3])
sample2 = np.array ([4, 5, 6])
dot_result = np.dot (sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15 17 20]
Years * 2: [ 2  6 10 14 20 24 30]
Dot Product: 32


### Try it for number 2:

In [36]:
# Try It: Subtraction, Division, and Exponential/Log [cite: 71, 72]
minus_ones = years_exp - 1
halved = years_exp / 2
log_vals = np.log(years_exp)

print("Minus 1:", minus_ones)
print("Halved:", halved)
print("Logarithm:", log_vals)

Minus 1: [ 0  2  4  6  9 11 14]
Halved: [0.5 1.5 2.5 3.5 5.  6.  7.5]
Logarithm: [0.         1.09861229 1.60943791 1.94591015 2.30258509 2.48490665
 2.7080502 ]


# 3. Indexing and Slicing

In [37]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])
# Step 2: Slice arrays
print("First two salaries:", salaries [0, 2]) # First two elements of first row
# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])
#Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: 70
Second column salaries: [ 60  90 120]
Last year of experience: 15


### Try it part for number 3:

In [38]:
# Try It: Reverse arrays and slice subgroups [cite: 82, 83]
reversed_exp = years_exp[::-1]
salary_slice = salaries[0:2, 1:3] # Top-left 2x2 section

print("Reversed Exp:", reversed_exp)
print("Salary Subgroup:\n", salary_slice)

Reversed Exp: [15 12 10  7  5  3  1]
Salary Subgroup:
 [[ 60  70]
 [ 90 100]]


# 4. Reshaping and Dimensions

In [39]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)
# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)
# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


### Try it part for number 4:


In [40]:
# Try It: Reshape into different dimensions [cite: 94]
# Reshaping 6 elements into a 3x2 matrix
new_shape = np.reshape(np.arange(1, 7), (3, 2))
print("3x2 Matrix:\n", new_shape)

3x2 Matrix:
 [[1 2]
 [3 4]
 [5 6]]


# 5. Broadcasting in NumPy


In [41]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array ([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus: \n", salaries_with_bonus)

Salaries after bonus: 
 [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]]


### Try it part for number 5:

In [42]:
# Try It: Multiply by a scaling factor [cite: 100]
scaled_salaries = salaries * 1.5 # 50% increase
print("Scaled Salaries:\n", scaled_salaries)

Scaled Salaries:
 [[ 75.  90. 105.]
 [120. 135. 150.]
 [165. 180. 195.]]


# 6. Statistical Operations

In [43]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))
# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))
# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))
# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 130 Min salary: 50
Sum of all salaries: 810


### Try it part for number 6:

In [44]:
# Try It: Median and Percentiles [cite: 112]
median_val = np.median(years_exp)
p90 = np.percentile(years_exp, 90)

print("Median:", median_val)
print("90th Percentile:", p90)

Median: 7.0
90th Percentile: 13.200000000000001


# 7. NumPy Functions on Arrays

In [45]:
#Step 1: Apply trigonometric functions
angles = np.array ([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos (angles))
# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 360]


### Try it part for number 7:

In [46]:
# Try It: Sqrt and custom function via apply_along_axis [cite: 120]
roots = np.sqrt(salaries)
row_sums = np.apply_along_axis(np.sum, 1, salaries)

print("Square Roots:\n", roots)
print("Sums per row:", row_sums)

Square Roots:
 [[ 7.07106781  7.74596669  8.36660027]
 [ 8.94427191  9.48683298 10.        ]
 [10.48808848 10.95445115 11.40175425]]
Sums per row: [180 270 360]


# 8. Integrating NumPy and Pandas for Analysis

In [47]:
import pandas as pd
# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))
#Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame (data, columns=['X', 'Y', 'Z'])
print("Generated Data: \n", df_data)
# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)
# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data: 
     X   Y   Z
0  47  29  46
1  17   2  47
2  32  48  39
3  18   5  29
4  14  31   4
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  47  29  46  3.850148  5.385165
1  17   2  47  2.833213  1.414214
2  32  48  39  3.465736  6.928203
3  18   5  29  2.890372  2.236068
4  14  31   4  2.639057  5.567764
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.480437  0.573826  0.990052  0.504257
Y       0.480437  1.000000 -0.165073  0.496463  0.988534
Z       0.573826 -0.165073  1.000000  0.626515 -0.233158
Log_X   0.990052  0.496463  0.626515  1.000000  0.502408
Sqrt_Y  0.504257  0.988534 -0.233158  0.502408  1.000000


### Try it part for number 8:

In [48]:
import pandas as pd

# Try It: Overall stats and square transformation [cite: 131, 132]
data = np.random.randint(1, 50, size=(5, 3))
df = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

print("Mean of columns:\n", df.mean())
print("Squared X values:\n", np.square(df['X']))

Mean of columns:
 X    20.0
Y    15.6
Z    22.6
dtype: float64
Squared X values:
 0      16
1      49
2    2025
3    1764
4       4
Name: X, dtype: int32


# 9. Importing and Summarizing Data Using Pandas

In [49]:
#Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")
# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame: \n", df_imported)
# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)
# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame: 
     X   Y   Z     Log_X    Sqrt_Y
0  47  29  46  3.850148  5.385165
1  17   2  47  2.833213  1.414214
2  32  48  39  3.465736  6.928203
3  18   5  29  2.890372  2.236068
4  14  31   4  2.639057  5.567764
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   25.600000  23.000000  33.000000  3.135705  4.306283
std    13.831124  19.300259  17.734148  0.504405  2.360066
min    14.000000   2.000000   4.000000  2.639057  1.414214
25%    17.000000   5.000000  29.000000  2.833213  2.236068
50%    18.000000  29.000000  39.000000  2.890372  5.385165
75%    32.000000  31.000000  46.000000  3.465736  5.567764
max    47.000000  48.000000  47.000000  3.850148  6.928203
Column Means:
 X         25.600000
Y         23.000000
Z         33.000000
Log_X      3.135705
Sqrt_Y     4.306283
dtype: float64
Column Standard Deviations:
 X         13.831124
Y         

### Try it part for number 9:

In [50]:
# Try It: Add calculated column and save [cite: 141, 142]
df['Sum_XY'] = df['X'] + df['Y']
df.to_csv('new_data.csv', index=False)

print("Updated DataFrame:\n", df.head())

Updated DataFrame:
     X   Y   Z  Sum_XY
0   4   1  28       5
1   7  11   1      18
2  45   6  41      51
3  42  15  37      57
4   2  45   6      47


# 10. Data Grouping and Aggregation

In [68]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df_kaggle = pd.read_csv('survey_results_public.csv')

# Step 2: Select relevant columns 
# FIX: The module says 'Years CodePro' but the file is 'YearsCodePro'
# FIX: The module says 'Converted Comp' but the file is 'ConvertedCompYearly'
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]

# Step 3: Clean the data
df_clean = df_subset.dropna()

# Step 4: Categorize experience (Fixed string comparison)
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'].astype(str) >= '10', 'Senior', 'Junior')

# Step 5: Group data
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()

# Step 6: Reset index
grouped_data = grouped_data.reset_index()
print(grouped_data.head())

       Country ExperienceLevel  ConvertedCompYearly
0  Afghanistan          Junior         1.773500e+03
1  Afghanistan          Senior         1.030717e+06
2      Albania          Junior         6.108000e+03
3      Albania          Senior         3.329794e+04
4      Algeria          Junior         1.402900e+04


C:\Users\VICTUS\AppData\Local\Temp\ipykernel_32148\1638148030.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'].astype(str) >= '10', 'Senior', 'Junior')


## Try it part for number 10:

In [69]:
import pandas as pd
import numpy as np

# --- 1. Load and Prepare Data ---
# We use the correct column names for the 2023 dataset
df_kaggle = pd.read_csv('survey_results_public.csv')
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
df_clean = df_subset.dropna()

print("--- TRY IT: STEP 10 RESULTS ---")

# --- 2. Change grouping to 'EdLevel' and compute Median ---
# Goal: See the middle salary for different education backgrounds
try_it_median = df_clean.groupby('EdLevel')['ConvertedCompYearly'].median()
print("\n1. Median Salary by Education Level:\n", try_it_median)

# --- 3. Compute Standard Deviation ---
# Goal: See how much salaries spread out/vary across the whole survey
try_it_std = df_clean['ConvertedCompYearly'].std()
print(f"\n2. Overall Standard Deviation of Compensation: {try_it_std:.2f}")

# --- 4. Explore top 10 countries with the highest average compensation ---
# Goal: Find the 10 countries where the mean (average) salary is highest
top_10_countries = df_clean.groupby('Country')['ConvertedCompYearly'].mean().sort_values(ascending=False).head(10)
print("\n3. Top 10 Countries by Average Compensation:\n", top_10_countries)

--- TRY IT: STEP 10 RESULTS ---

1. Median Salary by Education Level:
 EdLevel
Associate degree (A.A., A.S., etc.)                                                   72000.0
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          79556.0
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       74963.0
Primary/elementary school                                                             55764.0
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        80690.0
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    56757.0
Some college/university study without earning a degree                                69608.0
Something else                                                                        56514.5
Name: ConvertedCompYearly, dtype: float64

2. Overall Standard Deviation of Compensation: 682735.27

3. Top 10 Countries by Average Compensation:
 Country
Mali          