In [ ]:
#1
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jumar Sinues's Array: [ 84  56  14  20  61  38  98  73  93 101]
Mean: 63.8 Std Dev: 30.05262051801806


In [12]:
#2
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Jumar Sinues's Matrix:
 [[20 14 20 34]
 [ 9 29 37 37]
 [23 29 24 26]]
Row sums: [ 88 112 102]
Column sums: [52 72 81 97]


In [13]:
#3
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Jumar Sinues's 3D Array:
 [[[13  5  1]
  [ 8  4  4]
  [ 2  8  5]]

 [[ 5  7  1]
  [ 0  2  4]
  [ 7 17  3]]

 [[14 16  3]
  [ 7 11  1]
  [ 3  3 12]]]
Slice[:,1,:]:
 [[ 8  4  4]
 [ 0  2  4]
 [ 7 11  1]]


In [14]:
#4
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Jumar Sinues's Original: [ 84  56  14  20  61  38  98  73  93 101]
Filtered subset: [56 20 61 38]


In [ ]:
#5
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[20 14]
 [20 34]]
Matrix B:
 [[ 9 29]
 [37 37]]
A @ B:
 [[ 698 1098]
 [1438 1838]]
Determinant of A: 399.9999999999999


In [16]:
#6
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jumar Sinues's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [19]:
#7
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Jumar Sinues's Modified 4x4 Array:
 [[ 0 14  0 34]
 [ 9 29 37 37]
 [ 0 29  0 26]
 [ 3  6 27  2]]


In [20]:
#8
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Jumar Sinues's Scores: [ 83  55  13  19  60  37  97  72  92 100]
Grades: ['Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']


In [21]:
#9
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[20 14 20 34]
 [ 9 29 37 37]
 [23 29 24 26]]
Flattened: [20 14 20 34  9 29 37 37 23 29 24 26]
Transposed:
 [[20  9 23]
 [14 29 29]
 [20 37 24]
 [34 37 26]]


In [22]:
#10
import numpy as np
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 -1 -1]
 [-1  9 29]
 [37 37 23]]


In [23]:
#11
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50, 5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df)

           Name  Score  YearsCodePro
0  Jumar Sinues    101             5
1  Jumar Sinues     73             1
2  Jumar Sinues     31             8
3  Jumar Sinues     37             4
4  Jumar Sinues     78             4


In [25]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    112937.0
Master      136633.5
PhD         111571.0
Name: ConvertedComp, dtype: float64


In [26]:
#13
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
1          USA         146167
4      Germany         127100
0  Philippines         124691
2           UK         111571
3       Canada         101183


In [27]:
#14
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
high_exp = df[df['YearsCodePro'] > STUDENT_ID%10]
print(high_exp)

           Name  YearsCodePro
0  Jumar Sinues            13


In [28]:
#15
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         124691  100-150k
1         146167  100-150k
2         111571  100-150k
3         101183  100-150k
4         127100  100-150k


In [29]:
#16
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0         124691  11.733594
1         146167  11.892505
2         111571  11.622416
3         101183  11.524686
4         127100  11.752729


In [30]:
#17
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
 'ConvertedComp': np.random.randint(40000, 150000, 5) 
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.537566
ConvertedComp      0.537566       1.000000


In [31]:
#18
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
 'ConvertedComp': np.random.randint(40000, 150000, 5) 
})
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor  112937.0  112937.0  16622.666212
1    Master  136633.5  136633.5  13482.404997
2       PhD  111571.0  111571.0           NaN


In [32]:
#19
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
threshold = 110000
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0         124691     Yes
1         146167     Yes
2         111571     Yes
3         101183      No
4         127100     Yes


In [33]:
#20
import numpy as np
import pandas as pd
STUDENT_NAME = "Jumar Sinues"
STUDENT_ID = 4168

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada       101183.0  101183
Germany      127100.0  127100
Philippines  124691.0  124691
UK           111571.0  111571
USA          146167.0  146167
