# 1. Using try-except Blocks for Safe NumPy Operations 

In [1]:
import numpy as np 
try: 
 a = np.array([1, 2, 3]) 
 b = np.array([[1], [2], [3]]) 
 result = a + b 
 print(result) 
except ValueError as e: 
 print(f"Broadcasting error: {e}")


[[2 3 4]
 [3 4 5]
 [4 5 6]]


# 2. Creating and Using Identity Matrices in Computation 


In [2]:
identity = np.eye(3) 
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]]) 
print("Matrix + Identity:\n", matrix + identity) 

Matrix + Identity:
 [[ 3.  3.  4.]
 [ 1.  1.  6.]
 [ 7.  8. 10.]]


# 3. Detecting NaNs and Invalid Data in Arrays (NumPy)

In [4]:
data = np.array([1, 2, np.nan, 4, np.inf]) 
cleaned = data[np.isfinite(data)] 
print("Cleaned Data:", cleaned) 

Cleaned Data: [1. 2. 4.]


# 4. Handling Missing Data in Pandas

In [5]:
import pandas as pd 
df = pd.DataFrame({ 
 "Name": ["Alice", "Bob", "Charlie", None], 
 "Score": [85, None, 92, 88] 
}) 
df_cleaned = df.dropna() 
print("Cleaned DataFrame:\n", df_cleaned) 


Cleaned DataFrame:
       Name  Score
0    Alice   85.0
2  Charlie   92.0


# 5. Applying NumPy Functions to Pandas Columns 

In [6]:
df = pd.DataFrame({ 
 "X": [1, 2, 3], 
 "Y": [4, 5, 6] 
}) 
df["Log_X"] = np.log(df["X"]) 
df["Sqrt_Y"] = np.sqrt(df["Y"]) 
print("Transformed DataFrame:\n", df) 


Transformed DataFrame:
    X  Y     Log_X    Sqrt_Y
0  1  4  0.000000  2.000000
1  2  5  0.693147  2.236068
2  3  6  1.098612  2.449490
